### ISSUE TITLE
question: scrape_url how do you get response as markdown?

### ISSUE THREAD

**Issue by ShravanSunder** [spider-rs/spider-clients#5]
1. I'd like the website as a markdown
2. if i crawl a website with api as markdown, how do i get the file afterwards?

**Comment by j-mendez** [comment]
Hi @ShravanSunder , this would be possible if you first crawl the website with the normal UTF-8 encoded responses. Take the response and use `transform` to process the content as markdown. `return_content: bytes` will be available soon so that you can get the raw bytes if you need to download and not loose precision for things like images etc.
